import { Montserrat } from "next/font/google";
import "./globals.css";
import {
  PrimeReactProvider,
  PrimeReactContext,
  PrimeReact,
} from "primereact/api";

import Tailwind from "primereact/passthrough/tailwind";
import "primereact/resources/primereact.min.css";
import "primereact/resources/themes/lara-light-teal/theme.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const value = {
    ripple: true,
  };

  return (
    <html lang="en">
      <PrimeReactProvider value={value}>
        <body className={montserrat.className}>{children}</body>
      </PrimeReactProvider>
    </html>
  );
}
